SELECT (SELECT(SELECT FLOOR((
SELECT(
SELECT
(SELECT AVG(AD.FIYAT) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=4 )
*

(SELECT SUM(AD.MIKTAR) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=4) )
-
(
SELECT
(SELECT AVG(AD.FIYAT) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=1 AND AD.STOK_NO=4)
*
(SELECT SUM(AD.MIKTAR) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=4)
)
)
/
(SELECT
(SELECT AVG(AD.FIYAT) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=4)
*

(SELECT SUM(AD.MIKTAR) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=4) ) *100))

+
(SELECT FLOOR((
SELECT(
SELECT
(SELECT AVG(AD.FIYAT) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=3 )
*

(SELECT SUM(AD.MIKTAR) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=3) )
-
(
SELECT
(SELECT AVG(AD.FIYAT) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=1 AND AD.STOK_NO=3)
*
(SELECT SUM(AD.MIKTAR) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=3)
)
)
/
(SELECT
(SELECT AVG(AD.FIYAT) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=3)
*

(SELECT SUM(AD.MIKTAR) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=3) ) *100))

+


(SELECT FLOOR((
SELECT(
SELECT
(SELECT AVG(AD.FIYAT) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=1 )
*

(SELECT SUM(AD.MIKTAR) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=1) )
-
(
SELECT
(SELECT AVG(AD.FIYAT) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=1 AND AD.STOK_NO=1)
*
(SELECT SUM(AD.MIKTAR) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=1)
)
)
/
(SELECT
(SELECT AVG(AD.FIYAT) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=1)
*

(SELECT SUM(AD.MIKTAR) FROM ALSAT_DETAY AD
JOIN ALIS_SATIS A ON A.ALSAT_NO=AD.ALSAT_NO
WHERE A.ÝSLEM_YONU=-1 AND AD.STOK_NO=1) ) *100)))/(3)

